project: sl_rl_template
trial: train_sl_rl_v0

model1:
  kind: model
  module: sl_rl_template.models.model1
  checkpoint_interval: null
  max_batch_size: 1
  num_workers: 0
  cpus_per_worker: 0.5
  gpus_per_worker: 0.0
  memory_per_worker: 1024
  use_onnx: null
  local_mode: true
  override_model: true
  tensorboard_graph: true
  tensorboard_step: true

eval_source:
  kind: source
  enable: train
  module: sl_rl_template.sources.eval
  num_workers: null
  epoch: 1

train_source:
  kind: source
  enable: train
  module: sl_rl_template.sources.train
  num_workers: null
  epoch: 1

eval_buffer:
  kind: buffer
  enable: train
  sources:
    - eval_source
  size: 512
  batch_size: 128
  num_workers: 2
  density: 100

train_buffer:
  kind: buffer
  enable: train
  sources:
    - train_source
  size: 512
  batch_size: null
  num_workers: 2
  density: 100

rl_buffer:
  kind: buffer
  enable: train
  size: 512
  batch_size: 128
  num_workers: 2
  density: 100

agent1:
  kind: agent
  module: sl_rl_template.agents.agent1

actor1:
  kind: actor
  port: 9000
  num_workers: 2
  actors_per_worker: 10
  cpus_per_worker: 1.0
  memory_per_worker: 512
  use_tcp: false
  use_gateway: node
  agents:
    - agent1
  tick_input_proto:
    module: sl_rl_template.tick_pb2
    message: TickInput
  tick_output_proto:
    module: sl_rl_template.tick_pb2
    message: TickOutput
  episode_length: null
  environment: null

trainer1:
  kind: trainer
  enable: train
  module: sl_rl_template.trainers.trainer1
  use_gpu: null
  num_workers: null
  cpus_per_worker: null